// Mocks generated by Mockito 5.4.6 from annotations
// in interviews_flutter_assignment/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:interviews_flutter_assignment/core/services/connectivity_service.dart'
    as _i6;
import 'package:interviews_flutter_assignment/data/datasources/database_helper.dart'
    as _i3;
import 'package:interviews_flutter_assignment/data/models/application.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i3.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i4.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i4.Future<_i2.Database>);

  @override
  _i4.Future<void> insertApplication(_i5.Application? application) =>
      (super.noSuchMethod(
            Invocation.method(#insertApplication, [application]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Application>> getApplications() =>
      (super.noSuchMethod(
            Invocation.method(#getApplications, []),
            returnValue: _i4.Future<List<_i5.Application>>.value(
              <_i5.Application>[],
            ),
          )
          as _i4.Future<List<_i5.Application>>);

  @override
  _i4.Future<List<_i5.Application>> getApplicationsByJobId(String? jobId) =>
      (super.noSuchMethod(
            Invocation.method(#getApplicationsByJobId, [jobId]),
            returnValue: _i4.Future<List<_i5.Application>>.value(
              <_i5.Application>[],
            ),
          )
          as _i4.Future<List<_i5.Application>>);

  @override
  _i4.Future<void> updateApplicationSyncStatus(String? id, bool? synced) =>
      (super.noSuchMethod(
            Invocation.method(#updateApplicationSyncStatus, [id, synced]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Application>> getUnsyncedApplications() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedApplications, []),
            returnValue: _i4.Future<List<_i5.Application>>.value(
              <_i5.Application>[],
            ),
          )
          as _i4.Future<List<_i5.Application>>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i6.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<bool> get connectionStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectionStream),
            returnValue: _i4.Stream<bool>.empty(),
          )
          as _i4.Stream<bool>);

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
